version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: clerryha/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: clerryha/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: clerryha/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend 
    image: clerryha/udacity-frontend:local